openapi: 3.2.0
info:
  title: App Store Connect Webhook Pings API
  version: 4.3.1
  x-platforms:
    app_store_connect_api: App Store Connect API
  description: The App Store Connect API is the standards-based REST API Apple provides to automate tasks across App Store Connect, Xcode, and Certificates, Identifiers & Profiles.
servers:
- url: https://api.appstoreconnect.apple.com/
security:
- itc-bearer-token: []
tags:
- name: WebhookPings
paths:
  /v1/webhookPings:
    post:
      tags:
      - WebhookPings
      operationId: webhookPings_createInstance
      requestBody:
        description: WebhookPing representation
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookPingCreateRequest'
        required: true
      responses:
        '400':
          description: Parameter error(s)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized error(s)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable request entity error(s)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '201':
          description: Single WebhookPing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookPingResponse'
        '409':
          description: Request entity error(s)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Rate limit exceeded error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      summary: Create Webhook Pings
components:
  schemas:
    ErrorSourceParameter:
      type: object
      title: Parameter
      properties:
        parameter:
          type: string
      required:
      - parameter
    ResourceLinks:
      type: object
      properties:
        self:
          type: string
          format: uri-reference
    DocumentLinks:
      type: object
      properties:
        self:
          type: string
          format: uri-reference
      required:
      - self
    WebhookPingCreateRequest:
      type: object
      title: WebhookPingCreateRequest
      properties:
        data:
          type: object
          properties:
            type:
              type: string
              enum:
              - webhookPings
            relationships:
              type: object
              properties:
                webhook:
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          enum:
                          - webhooks
                        id:
                          type: string
                      required:
                      - id
                      - type
                  required:
                  - data
              required:
              - webhook
          required:
          - relationships
          - type
      required:
      - data
    ErrorLinks:
      type: object
      properties:
        about:
          type: string
          format: uri-reference
        associated:
          oneOf:
          - type: string
            format: uri-reference
          - type: object
            properties:
              href:
                type: string
                format: uri-reference
              meta:
                type: object
                properties:
                  source:
                    type: string
    WebhookPingResponse:
      type: object
      title: WebhookPingResponse
      properties:
        data:
          $ref: '#/components/schemas/WebhookPing'
        links:
          $ref: '#/components/schemas/DocumentLinks'
      required:
      - data
      - links
    ErrorSourcePointer:
      type: object
      title: JsonPointer
      properties:
        pointer:
          type: string
      required:
      - pointer
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              status:
                type: string
              code:
                type: string
              title:
                type: string
              detail:
                type: string
              source:
                oneOf:
                - $ref: '#/components/schemas/ErrorSourcePointer'
                - $ref: '#/components/schemas/ErrorSourceParameter'
              links:
                $ref: '#/components/schemas/ErrorLinks'
              meta:
                type: object
                additionalProperties: {}
            required:
            - code
            - detail
            - status
            - title
    WebhookPing:
      type: object
      title: WebhookPing
      properties:
        type:
          type: string
          enum:
          - webhookPings
        id:
          type: string
        links:
          $ref: '#/components/schemas/ResourceLinks'
      required:
      - id
      - type
  securitySchemes:
    itc-bearer-token:
      type: http
      scheme: bearer
      bearerFormat: JWT
